INSERT INTO permission (permission_text, permission_unique_text, module_name) VALUES ('Dashboard', 'dashboard', 'dashboard');
INSERT INTO permission (permission_text, permission_unique_text, module_name) VALUES ('Custom Order', 'custom_order', 'custom_order');
INSERT INTO permission (permission_text, permission_unique_text, module_name) VALUES ('Squarespace', 'squarespace', 'squarespace');
INSERT INTO permission (permission_text, permission_unique_text, module_name) VALUES ('Routific', 'routific', 'routific');
INSERT INTO permission (permission_text, permission_unique_text, module_name) VALUES ('Get labels/tags', 'get_labels_tags', 'get_labels_tags');
INSERT INTO permission (permission_text, permission_unique_text, module_name) VALUES ('Plan a Project', 'plan_a_project', 'plan_a_project');
INSERT INTO permission (permission_text, permission_unique_text, module_name) VALUES ('Customer lookup', 'customer_lookup', 'customer_lookup');
INSERT INTO permission (permission_text, permission_unique_text, module_name) VALUES ('Delivery dates/zones', 'delivery_dates_zones', 'delivery_dates_zones');
INSERT INTO permission (permission_text, permission_unique_text, module_name) VALUES ('User Management', 'user_management', 'user_management');
INSERT INTO permission (permission_text, permission_unique_text, module_name) VALUES ('Drivers', 'drivers', 'drivers');
INSERT INTO permission (permission_text, permission_unique_text, module_name) VALUES ('Events', 'events', 'events');
INSERT INTO permission (permission_text, permission_unique_text, module_name) VALUES ('Sales/Outreach', 'sales_outreach', 'sales_outreach');
INSERT INTO permission (permission_text, permission_unique_text, module_name) VALUES ('Operations', 'operations', 'operations');
INSERT INTO permission (permission_text, permission_unique_text, module_name) VALUES ('Volunteer Days Management', 'volunteer_days_management', 'volunteer_days_management');
INSERT INTO permission (permission_text, permission_unique_text, module_name) VALUES ('Grants', 'grants', 'grants');
INSERT INTO permission (permission_text, permission_unique_text, module_name) VALUES ('Settings', 'settings', 'settings');
INSERT INTO permission (permission_text, permission_unique_text, module_name) VALUES ('Employee Section', 'employee_section', 'employee_section');
INSERT INTO permission (permission_text, permission_unique_text, module_name) VALUES ('Employee Management', 'employee_management', 'employee_management');
INSERT INTO permission (permission_text, permission_unique_text, module_name) VALUES ('Youth Management', 'youth_management', 'youth_management');
INSERT INTO permission (permission_text, permission_unique_text, module_name) VALUES ('Email Outreach', 'email_outreach', 'email_outreach');
INSERT INTO permission (permission_text, permission_unique_text, module_name) VALUES ('Master Calendar', 'master_calendar', 'master_calendar');